sudo: required
language: generic 
services:
 - docker
 
before_install:
 - docker build -t moliwhale/docker-react -f Dockerfile.dev .
 
script:
 - docker run -e CI=true moliwhale/docker-react npm run test
